# Generated by Django 5.0.3 on 2025-03-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_user_delete_web3user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(default='<function uuid4 at 0x00000274C8586660>', max_length=255),
        ),
    ]
